services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4444:4200"
    volumes:
      - ./Frontend/src:/app/src
    depends_on:
      - backend

  backend:
    build:
      context: ./WebAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServerConnection=Server=db;Database=invoicikaDb;User=sa;Password=invoicika!123;Trusted_Connection=False;MultipleActiveResultSets=true;
    depends_on:
      - db
    volumes:
      - ./WebAPI:/app/webapi
    networks:
      - invoicika_backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=invoicika!123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - invoicika_backend
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1433"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

networks:
  invoicika_backend:

volumes:
  sql_data:
